# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_reftext', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_no', models.IntegerField(default=99)),
                ('article_title', models.CharField(max_length=250)),
                ('article_body', models.CharField(max_length=100000)),
                ('article_date', models.CharField(default='December 2017', max_length=100)),
                ('article_link', models.CharField(default='#', max_length=100)),
                ('article_publisher', models.CharField(default='publisher', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_pubdate', models.DateTimeField(verbose_name='date published')),
                ('question_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Article')),
                ('question_madeby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_no', models.PositiveIntegerField(default=1)),
                ('research_keyword', models.CharField(max_length=50)),
                ('research_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_no', models.IntegerField(default=0)),
                ('survey_name', models.CharField(max_length=100)),
                ('survey_link', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='genquestion',
            name='question_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Research'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Research'),
        ),
        migrations.AddField(
            model_name='annotquestion',
            name='question_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Article'),
        ),
        migrations.AddField(
            model_name='annotquestion',
            name='question_madeby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotquestion',
            name='question_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Research'),
        ),
    ]
