# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20180614_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotquestion',
            old_name='question_deletdate',
            new_name='question_deletedate',
        ),
    ]
