# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20180614_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='genquestion',
            name='question_deletedate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date deleted'),
            preserve_default=False,
        ),
    ]
