# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0005_genquestion_question_deletedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_order', models.IntegerField(default=0)),
                ('session_starttime', models.DateTimeField(verbose_name='date published')),
                ('session_endtime', models.DateTimeField(verbose_name='date published')),
                ('session_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Article')),
                ('session_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Research')),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='annotquestion',
            name='question_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genquestion',
            name='question_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
