# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0006_auto_20180614_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_id', models.CharField(max_length=200)),
                ('question_reftext', models.CharField(max_length=200)),
                ('question_description', models.CharField(max_length=200)),
                ('question_importance', models.IntegerField(default=4)),
                ('question_pubdate', models.DateTimeField(verbose_name='date published')),
                ('question_deleted', models.BooleanField(default=False)),
                ('question_deletedate', models.DateTimeField(verbose_name='date deleted')),
                ('question_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Article')),
                ('question_madeby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Research')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_id', models.CharField(max_length=200)),
                ('question_reftext', models.CharField(max_length=200)),
                ('question_description', models.CharField(max_length=200)),
                ('question_importance', models.IntegerField(default=4)),
                ('question_pubdate', models.DateTimeField(verbose_name='date published')),
                ('question_deleted', models.BooleanField(default=False)),
                ('question_deletedate', models.DateTimeField(verbose_name='date deleted')),
                ('question_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Article')),
                ('question_madeby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Research')),
            ],
        ),
        migrations.RemoveField(
            model_name='annotquestion',
            name='question_article',
        ),
        migrations.RemoveField(
            model_name='annotquestion',
            name='question_madeby',
        ),
        migrations.RemoveField(
            model_name='annotquestion',
            name='question_research',
        ),
        migrations.RemoveField(
            model_name='genquestion',
            name='question_article',
        ),
        migrations.RemoveField(
            model_name='genquestion',
            name='question_madeby',
        ),
        migrations.RemoveField(
            model_name='genquestion',
            name='question_research',
        ),
        migrations.DeleteModel(
            name='AnnotQuestion',
        ),
        migrations.DeleteModel(
            name='GenQuestion',
        ),
    ]
