# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20180625_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstat',
            name='seeeion_mode',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
