# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_sessionstat_seeeion_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionstat',
            old_name='seeeion_mode',
            new_name='session_mode',
        ),
    ]
