# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0009_auto_20180627_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_order', models.IntegerField(default=0)),
                ('survey_starttime', models.DateTimeField(verbose_name='date published')),
                ('survey_endtime', models.DateTimeField(verbose_name='date published')),
                ('survey_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Article')),
                ('survey_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Research')),
                ('survey_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
