# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_surveystat_survey_eval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstat',
            name='session_html',
            field=models.CharField(default='', max_length=99999999),
            preserve_default=False,
        ),
    ]
